apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portale-ingress
  namespace: portale-quotazioni-2-fe
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

