apiVersion: v1
kind: Secret
metadata:
  name: portale-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.db.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
  DB_NAME: {{ .Values.db.db | b64enc | quote }}
  JWT_SECRET: {{ .Values.backend.jwtSecret | b64enc | quote }}
  ADMIN_DEFAULT_PASSWORD: {{ .Values.backend.adminDefaultPassword | b64enc | quote }}
  SMTP_PASS: {{ .Values.backend.smtpPass | b64enc | quote }}
