frontend:
  image: frontend:latest
  replicaCount: 1
  ingress:
    enabled: true
    host: portale.local
backend:
  image: backend:latest
  replicaCount: 1
  ingress:
    enabled: true
    host: api.portale.local
  jwtSecret: CHANGE_ME_JWT_SECRET_MIN_32_CHARS
  adminDefaultPassword: CHANGE_ME_ADMIN_PASSWORD
  smtpPass: CHANGE_ME_SMTP_APP_PASSWORD
db:
  image: postgres:15-alpine
  storage: 5Gi
  user: portale_user
  password: CHANGE_ME_DB_PASSWORD
  db: portaledb
