import { Injectable, Logger } from '@nestjs/common';
import { BedrockService } from '../../bedrock/bedrock.service';
import { KnowledgeLoaderService } from '../../knowledge/knowledge-loader.service';
import { EstimationResult } from '../estimation/estimation.service';
import * as fs from 'fs';
import * as path from 'path';

export interface ValidationResult {
  estimation_id: string;
  validation_data: {
    decision: 'APPROVE' | 'REVIEW' | 'SENIOR_REVIEW' | 'REJECT';
    confidence: number;
    summary: {
      total_checks: number;
      passed: number;
      warnings: number;
      errors: number;
    };
    issues: Array<{
      severity: 'HIGH' | 'MEDIUM' | 'LOW';
      category: string;
      message: string;
      recommendation?: string;
    }>;
    metrics: {
      cost_per_vcpu: number;
      cost_per_tb: number;
      opex_capex_ratio: number;
    };
    next_steps: string[];
  };
  validated_by: string;
  validated_at: string;
}

@Injectable()
export class ValidationAgentService {
  private readonly logger = new Logger(ValidationAgentService.name);
  private readonly agentSkill: string;

  constructor(
    private readonly bedrockService: BedrockService,
    private readonly knowledgeLoader: KnowledgeLoaderService,
  ) {
    const skillPath = path.join(__dirname, 'validation.prompt.md');
    if (fs.existsSync(skillPath)) {
      this.agentSkill = fs.readFileSync(skillPath, 'utf-8');
      this.logger.log('Validation agent skill loaded from validation.prompt.md');
    } else {
      this.logger.warn('Validation agent skill file not found, using embedded prompt');
      this.agentSkill = this.getDefaultPrompt();
    }
  }

  /**
   * Validate an estimation
   */
  async validateEstimation(
    estimationId: string,
    estimation: EstimationResult,
  ): Promise<ValidationResult> {
    this.logger.log(`[VALIDATION-AGENT] ═══════════════════════════════════════════`);
    this.logger.log(`[VALIDATION-AGENT] Starting Validation Agent`);
    this.logger.log(`[VALIDATION-AGENT] Estimation ID: ${estimationId}`);
    this.logger.log(`[VALIDATION-AGENT] Quotation ID: ${estimation.quotation_id}`);
    this.logger.log(`[VALIDATION-AGENT] ═══════════════════════════════════════════`);

    const knowledgeBaseString = this.knowledgeLoader.getKnowledgeAsString();

    const systemPrompt = this.buildSystemPrompt(knowledgeBaseString);
    const userMessage = this.buildUserMessage(estimation);

    const startTime = Date.now();

    try {
      this.logger.log(`[VALIDATION-AGENT] Invoking AI model for validation...`);
      const response = await this.bedrockService.invoke({
        system: systemPrompt,
        systemCacheable: true, // Enable prompt caching for validation rules
        messages: [
          {
            role: 'user',
            content: userMessage,
          },
        ],
        maxTokens: 16000,
        temperature: 1.0,
      });

      const latency = Date.now() - startTime;
      const cacheInfo = response.usage.cacheReadInputTokens
        ? ` [CACHE HIT: ${response.usage.cacheReadInputTokens} tokens, ~90% cost savings]`
        : response.usage.cacheCreationInputTokens
        ? ` [CACHE CREATED: ${response.usage.cacheCreationInputTokens} tokens]`
        : '';

      this.logger.log(`[VALIDATION-AGENT] Response received in ${latency}ms (${(latency/1000).toFixed(1)}s)`);
      this.logger.log(`[VALIDATION-AGENT] Tokens: input=${response.usage.inputTokens}, output=${response.usage.outputTokens}${cacheInfo}`);

      const validationData = this.parseValidationResponse(response.content);

      this.logger.log(`[VALIDATION-AGENT] Decision: ${validationData.decision}`);
      this.logger.log(`[VALIDATION-AGENT] Issues found: ${validationData.issues?.length || 0}`);
      if (validationData.issues && validationData.issues.length > 0) {
        const high = validationData.issues.filter(i => i.severity === 'HIGH').length;
        const medium = validationData.issues.filter(i => i.severity === 'MEDIUM').length;
        const low = validationData.issues.filter(i => i.severity === 'LOW').length;
        this.logger.log(`[VALIDATION-AGENT] Issues breakdown: HIGH=${high}, MEDIUM=${medium}, LOW=${low}`);
      }
      this.logger.log(`[VALIDATION-AGENT] ═══════════════════════════════════════════`);

      return {
        estimation_id: estimationId,
        validation_data: validationData,
        validated_by: 'validation-agent-v1',
        validated_at: new Date().toISOString(),
      };
    } catch (error) {
      this.logger.error(`Failed to validate estimation: ${error.message}`);
      throw error;
    }
  }

  private buildSystemPrompt(knowledgeBase: string): string {
    return `${this.agentSkill}

## Knowledge Base (for reference)

${knowledgeBase}`;
  }

  private buildUserMessage(estimation: EstimationResult): string {
    return `Validate the following cost estimation:

## Estimation Details

**Quotation ID:** ${estimation.quotation_id}
**Generated By:** ${estimation.generated_by}
**Generated At:** ${estimation.generated_at}

## Estimation Data

\`\`\`json
${JSON.stringify(estimation.estimation_data, null, 2)}
\`\`\`

Please perform a complete validation following your instructions and provide the validation report.`;
  }

  private parseValidationResponse(content: string): any {
    const jsonMatch = content.match(/```json\n([\s\S]+?)\n```/);
    const jsonString = jsonMatch ? jsonMatch[1] : content;

    try {
      return JSON.parse(jsonString);
    } catch (error) {
      this.logger.error(`Failed to parse validation response: ${error.message}`);
      throw new Error('Invalid validation response format');
    }
  }

  private getDefaultPrompt(): string {
    return `You are an AI validation agent for IT cost estimations.

Your role is to verify:
1. Mathematical accuracy (formulas, totals, projections)
2. Threshold compliance (cost/vCPU, cost/TB, ratios)
3. Mandatory components (QA ≥10%, governance costs)
4. Formula verification (VMware, OpenShift, Dynatrace)

Output Format (JSON):
{
  "decision": "APPROVE|REVIEW|SENIOR_REVIEW|REJECT",
  "confidence": number (0-100),
  "summary": {
    "total_checks": number,
    "passed": number,
    "warnings": number,
    "errors": number
  },
  "issues": [ ... ],
  "metrics": { ... },
  "next_steps": [ ... ]
}

Confidence Scoring:
- >85%: HIGH → AI_VALIDATED (auto-approve)
- 70-85%: MEDIUM → AI_NEEDS_REVIEW (human review)
- <70%: LOW → AI_REJECTED (reject, needs correction)`;
  }
}
